<!doctype html>

<html lang="en">

<head>
  <title>Wrapping Up Rails Exceptional Behavior - Kevin Murphy</title>
  <meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta name="description" content="In our last post, we encountered some inconsistent behavior between Rails 5 and Rails 6. Now that we&#39;ve identified the inconsistency, we&#39;ll explain why it&#39;s happening." />
<meta name="author" content="Kevin Murphy" /><meta property="og:title" content="Wrapping Up Rails Exceptional Behavior" />
<meta property="og:description" content="In our last post, we encountered some inconsistent behavior between Rails 5 and Rails 6. Now that we&#39;ve identified the inconsistency, we&#39;ll explain why it&#39;s happening." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://kevinjmurphy.com/posts/wrapping-up-rails-exceptional-behavior/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2021-03-28T14:15:20-04:00" />
<meta property="article:modified_time" content="2021-03-28T14:15:20-04:00" />


<meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="Wrapping Up Rails Exceptional Behavior"/>
<meta name="twitter:description" content="In our last post, we encountered some inconsistent behavior between Rails 5 and Rails 6. Now that we&#39;ve identified the inconsistency, we&#39;ll explain why it&#39;s happening."/>

<meta name="generator" content="Hugo 0.88.1" />
    

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css" integrity="sha256-l85OmPOjvil/SOvVt3HnSSjzF1TUMyT9eV0c2BzEGzU=" crossorigin="anonymous" />
  <link rel="stylesheet" href="https://kevinjmurphy.com/fontawesome/css/all.min.css" />
  
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Slab|Ruda" />
  
  
  <link rel="stylesheet" type="text/css" href="https://kevinjmurphy.com/css/styles.css" /><link rel='stylesheet' href='https://kevinjmurphy.com/css/link-style.css'><link rel='stylesheet' href='https://kevinjmurphy.com/css/code-scroll.css'><link rel='stylesheet' href='https://kevinjmurphy.com/css/coverage-emoji.css'></head>

<body>
  <div id="container">
    <header>
      <h1>
                <a href="https://kevinjmurphy.com/">Kevin Murphy</a>
            </h1>

      <ul id="social-media">
             <li>
               <a href="https://github.com/kevin-j-m" title="GitHub">
               <i class="fab fa-github fa-lg"></i>
               </a>
             </li>
             <li>
               <a href="https://twitter.com/kevin_j_m" title="Twitter">
               <i class="fab fa-twitter fa-lg"></i>
               </a>
             </li>
             <li>
               <a href="https://linkedin.com/in/kevinmurphydev" title="LinkedIn">
               <i class="fab fa-linkedin fa-lg"></i>
               </a>
             </li>
             <li>
               <a href="https://dev.to/kevin_j_m" title="devto">
               <i class="fab fa-dev fa-lg"></i>
               </a>
             </li>
      </ul>
      
      <p><em>Software Developer</em></p>
      
    </header>

    
<nav>
    <ul>
        
        <li>
            <a class="" href="https://kevinjmurphy.com/">
                <i class="fa-li fa  fa-lg"></i><span>Home</span>
            </a>
        </li>
        
        <li>
            <a class="" href="https://kevinjmurphy.com/about/">
                <i class="fa-li fa  fa-lg"></i><span>About</span>
            </a>
        </li>
        
        <li>
            <a class="" href="https://kevinjmurphy.com/speaking/">
                <i class="fa-li fa  fa-lg"></i><span>Speaking</span>
            </a>
        </li>
        
    </ul>
</nav>


    <main>




<article>

    <h1>Wrapping Up Rails Exceptional Behavior</h1>

    
      <aside>
    <ul>
        <li>
            <time class="post-date" datetime="2021-03-28T14:15:20-04:00">Mar 28, 2021</time>
        </li>
        
        

        
        <li>
            <em>
                
                    
                    <a href="https://kevinjmurphy.com/tags/ruby">#ruby</a>
                
                    , 
                    <a href="https://kevinjmurphy.com/tags/rails">#rails</a>
                
                    , 
                    <a href="https://kevinjmurphy.com/tags/debugging">#debugging</a>
                
            </em>
        </li>
        

        <li>3 minute read</li>
    </ul>
</aside>

    

    


    <h2 id="exceptional-behavior-in-rails">Exceptional Behavior in Rails <a href="#exceptional-behavior-in-rails">ðŸ”—</a></h2>
<ol>
<li><a href="https://kevinjmurphy.com/posts/wrapping-about-exceptional-behavior-in-rails/">(W)rapping About Exceptional Behavior In Rails</a></li>
<li><strong>Wrapping Up Rails Exceptional Behavior</strong></li>
</ol>
<h2 id="reset">Reset <a href="#reset">ðŸ”—</a></h2>
<p>In our <a href="https://kevinjmurphy.com/posts/wrapping-about-exceptional-behavior-in-rails/">last post</a>, we
encountered some inconsistent behavior between Rails 5 and Rails 6. In Rails 5,
raising a <code>RuntimeError</code> in a controller after rescuing from an
<code>ActiveRecord::RecordNotFound</code> exception was still returning a 404 HTTP status
code. In Rails 6, the status code is a 500.</p>
<p>We looked around, and we think we&rsquo;ve isolated the area of interest to be in the
<code>ExceptionWrapper</code> <a href="https://github.com/rails/rails/blob/63d3f3f4d868a5ed9eacf00af2a80278aa005051/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb">class</a>.</p>
<h2 id="revisit-the-wrapper">Revisit The Wrapper <a href="#revisit-the-wrapper">ðŸ”—</a></h2>
<p>We looked into what was creating our wrapper and discovered that we were always
passing it the <code>RuntimeError</code>. After taking a much-needed break, we start
reading the code again, and, almost immediately, we see a <a href="https://github.com/rails/rails/blob/63d3f3f4d868a5ed9eacf00af2a80278aa005051/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb#L36">transformation</a>:</p>
<pre tabindex="0"><code class="language-ruby{3}" data-lang="ruby{3}">def initialize(backtrace_cleaner, exception)
  @backtrace_cleaner = backtrace_cleaner
  @exception = original_exception(exception)
end
</code></pre><p>The exception that is passed in is modified. Let&rsquo;s look at this
<code>original_exception</code> <a href="https://github.com/rails/rails/blob/63d3f3f4d868a5ed9eacf00af2a80278aa005051/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb#L106-L112">method</a>.</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-ruby" data-lang="ruby"><span style="color:#66d9ef">def</span> <span style="color:#a6e22e">original_exception</span>(exception)
  <span style="color:#66d9ef">if</span> @@rescue_responses<span style="color:#f92672">.</span>has_key?(exception<span style="color:#f92672">.</span>cause<span style="color:#f92672">.</span>class<span style="color:#f92672">.</span>name)
    exception<span style="color:#f92672">.</span>cause
  <span style="color:#66d9ef">else</span>
    exception
  <span style="color:#66d9ef">end</span>
<span style="color:#66d9ef">end</span>
</code></pre></div><p>Recall that our <code>RuntimeError</code> is raised as a result of handling an
<code>ActiveRecord::RecordNotFound</code> exception. The <code>RecordNotFound</code> exception <strong>is</strong> the
<a href="https://ruby-doc.org/core-3.0.0/Exception.html#method-i-cause">cause</a> of the <code>RuntimeError</code>. We previously discovered that <code>RecordNotFound</code> is added to <code>@@rescue_responses</code> in ActiveRecord&rsquo;s <a href="https://github.com/rails/rails/blob/d75c2a175215c0f6d011b60f1c9f2b6466184adb/activerecord/lib/active_record/railtie.rb#L22-L27">railtie</a>.</p>
<p>The cause of our exception is in the hash, and as such, the <strong>cause</strong> is set as
the <code>@exception</code> variable in the initializer. That cause is <code>RecordNotFound</code>,
and a <code>RecordNotFound</code> exception is supposed to return a 404 status code.</p>
<p>We can now explain why a 404 is returned!</p>
<h2 id="regifting-rails-6-redux">Regifting (Rails 6 Redux) <a href="#regifting-rails-6-redux">ðŸ”—</a></h2>
<p>We now have a handle on the behavior in Rails 5; however, this investigation
started because we noticed it was different in Rails 5 and Rails 6. Let&rsquo;s check
in on the <code>ExceptionWrapper</code> initializer in <a href="https://github.com/rails/rails/blob/0440369d03ae99f9f044b00e39dcd3d9871c65c2/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb#L46-L48">Rails 6</a>.</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-ruby" data-lang="ruby"><span style="color:#66d9ef">def</span> <span style="color:#a6e22e">initialize</span>(backtrace_cleaner, exception)
  @backtrace_cleaner <span style="color:#f92672">=</span> backtrace_cleaner
  @exception <span style="color:#f92672">=</span> exception
<span style="color:#66d9ef">end</span>
</code></pre></div><p>No longer are we retrieving the <code>original_exception</code>. That doesn&rsquo;t tell the
whole story though. When we ask for the <a href="https://github.com/rails/rails/blob/4c78cc8b04861f02d660aefc37979eb2244db6ba/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb#L62">status code</a>, we&rsquo;re not using <code>@exception</code>. Instead, we now have an <code>unwrapped_exception</code> to <a href="https://github.com/rails/rails/blob/4c78cc8b04861f02d660aefc37979eb2244db6ba/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb#L49-L55">investigate</a>.</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-ruby" data-lang="ruby"><span style="color:#66d9ef">def</span> <span style="color:#a6e22e">unwrapped_exception</span>
  <span style="color:#66d9ef">if</span> wrapper_exceptions<span style="color:#f92672">.</span>include?(exception<span style="color:#f92672">.</span>class<span style="color:#f92672">.</span>to_s)
    exception<span style="color:#f92672">.</span>cause
  <span style="color:#66d9ef">else</span>
    exception
  <span style="color:#66d9ef">end</span>
<span style="color:#66d9ef">end</span>
</code></pre></div><p>Rather than looking in <code>rescue_responses</code>, we&rsquo;re now looking in
<code>wrapper_exceptions</code>, which it appears is a <a href="https://github.com/rails/rails/blob/4c78cc8b04861f02d660aefc37979eb2244db6ba/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb#L35-L37">list</a> of one exception that should
behave particularly exceptionally.</p>
<p>If the exception is an <code>ActionView::Template::Error</code>, then look up the status
code based on the cause of the exception. Otherwise, determine it based on the
exception itself.</p>
<p><code>RuntimeError</code> isn&rsquo;t in this list of <code>wrapper_exceptions</code>, so we don&rsquo;t use the
cause (<code>ActiveRecord::RecordNotFound</code>) to determine the status code. We use the
<code>RuntimeError</code> itself. That has no special handling in <code>rescue_responses</code>, so a
500 HTTP status code is returned.</p>
<h2 id="thank-you-card">Thank You Card <a href="#thank-you-card">ðŸ”—</a></h2>
<p>The <a href="https://github.com/rails/rails/pull/35049/commits/ef40fb6fd88f2e3c3f989aef65e3ddddfadee814">commit</a> that makes this change contains a very well-worded description of this scenario, including:</p>
<blockquote>
<p>When the cause is mapped to an HTTP status code the last exception is unexpectedly uwrapped</p>
</blockquote>
<p>Thanks to <a href="https://github.com/yuki24">Yuki Nishijima</a> for fixing this!</p>
<blockquote>
<p>This post originally published on <a href="https://blog.thegnar.co/wrapping-up-rails-exceptional-behavior">The Gnar Company blog</a>.</p>
</blockquote>


</article>


<section class="post-nav">
    <ul>
        
        <li>
            <a href="https://kevinjmurphy.com/posts/wrapping-about-exceptional-behavior-in-rails/"><i class="fa fa-chevron-circle-left"></i> (W)rapping About Exceptional Behavior in Rails</a>
        </li>
        
        
        <li>
            <a href="https://kevinjmurphy.com/posts/to-change-or-not-to-change/">To Change or Not to Change <i class="fa fa-chevron-circle-right"></i> </a>
        </li>
        
    </ul>
</section>
  
    
    
  





</main>
    <footer>
        <h6>Copyright Â© 2021 - Kevin Murphy |
            Rendered by <a href="https://gohugo.io" title="Hugo">Hugo</a> |
            <a href="https://kevinjmurphy.com/index.xml">Subscribe </a></h6>
    </footer>
</div>
<script src="https://kevinjmurphy.com/js/scripts.js"></script>


</body>

</html>

